// VS Code integration for Expressa: completion, hover, signature help and
// go to definition. Syntax highlighting is the TextMate grammar in
// syntaxes/; the data about native functions comes from nativas.json
// (generated by scripts/gerar.js).

'use strict';

const fs = require('fs');
const path = require('path');
const vscode = require('vscode');
const a = require('./analise');
const DATA = require('./nativas.json');

const LANG = 'expressa';
const KEYWORDS = Object.values(DATA.keywords).flat();

/** name or alias -> native entry */
const NATIVE = new Map();
for (const n of DATA.nativas) {
  NATIVE.set(n.name, n);
  for (const al of n.aliases) NATIVE.set(al, n);
}

// ── Imported files ────────────────────────────────────────────────────────

const fileCache = new Map(); // path -> { mtime, defs }

/** Top-level definitions of a `.lep` file, cached by modification time.
 * Open editors win over the disk so unsaved changes are seen. */
function fileDefinitions(file) {
  const open = vscode.workspace.textDocuments.find((d) => d.uri.fsPath === file);
  if (open) return a.parseDefinitions(open.getText(), KEYWORDS).filter((d) => d.topLevel);
  let stat;
  try {
    stat = fs.statSync(file);
  } catch {
    return [];
  }
  const hit = fileCache.get(file);
  if (hit && hit.mtime === stat.mtimeMs) return hit.defs;
  let defs = [];
  try {
    defs = a.parseDefinitions(fs.readFileSync(file, 'utf8'), KEYWORDS).filter((d) => d.topLevel);
  } catch {
    // unreadable: no names
  }
  fileCache.set(file, { mtime: stat.mtimeMs, defs });
  return defs;
}

/** What a document can see: imports split into native and file modules. */
function scope(doc) {
  const text = doc.getText();
  const imports = a.parseImports(text);
  const spread = new Set(); // native modules imported without alias
  const aliases = new Map(); // alias -> { native } | { file }
  const files = []; // spread file imports
  for (const imp of imports) {
    const native = a.nativeModule(imp.spec, DATA.modules);
    const target = native ? { native } : { file: a.resolveImport(imp.spec, doc.uri.fsPath) };
    if (imp.alias) aliases.set(imp.alias, target);
    else if (native) spread.add(native);
    else files.push(target.file);
  }
  return { text, imports, spread, aliases, files, defs: a.parseDefinitions(text, KEYWORDS) };
}

// ── Presentation ──────────────────────────────────────────────────────────

function nativeMarkdown(n, withSignatures = true) {
  const md = new vscode.MarkdownString();
  if (withSignatures && n.signatures.length) md.appendCodeblock(n.signatures.join('\n'), LANG);
  if (n.module) md.appendMarkdown(`Módulo \`${n.module}\`: \`importe "${n.module}"\`\n\n`);
  if (n.aliases.length) md.appendMarkdown(`Também: ${n.aliases.map((x) => `\`${x}\``).join(', ')}\n\n`);
  md.appendMarkdown(n.doc || n.summary);
  return md;
}

function defSignature(d) {
  return d.kind === 'funcao' ? `${d.name}(${d.params.join(', ')})` : d.name;
}

function defMarkdown(d, where) {
  const md = new vscode.MarkdownString();
  md.appendCodeblock(d.kind === 'funcao' ? `${d.name} = funcao(${d.params.join(', ')})` : d.name, LANG);
  md.appendMarkdown(where);
  return md;
}

function callSnippet(name, params) {
  if (!params.length) return new vscode.SnippetString(`${name}()`);
  return new vscode.SnippetString(`${name}($1)`);
}

function nativeItem(n, name, { method = false, importEdit = null } = {}) {
  const item = new vscode.CompletionItem(name, n.kind === 'valor' ? vscode.CompletionItemKind.Variable : vscode.CompletionItemKind.Function);
  item.detail = n.signatures[0] || n.summary;
  item.documentation = nativeMarkdown(n);
  item.label = { label: name, description: n.module ? `importe "${n.module}"` : 'nativa' };
  if (n.kind === 'funcao') {
    const params = a.signatureParams(n.signatures[0] || '');
    item.insertText = callSnippet(name, method ? params.slice(1) : params);
    item.command = { command: 'editor.action.triggerParameterHints', title: '' };
  }
  if (importEdit) {
    item.additionalTextEdits = [importEdit];
    item.detail = `${item.detail}  (adiciona importe "${n.module}")`;
  }
  return item;
}

function defItem(d, where, method = false) {
  const kind = d.kind === 'funcao' ? vscode.CompletionItemKind.Function : d.kind === 'modulo' ? vscode.CompletionItemKind.Module : vscode.CompletionItemKind.Variable;
  const item = new vscode.CompletionItem({ label: d.name, description: where }, kind);
  item.detail = defSignature(d);
  if (d.kind === 'funcao') {
    item.insertText = callSnippet(d.name, method ? d.params.slice(1) : d.params);
    item.command = { command: 'editor.action.triggerParameterHints', title: '' };
  }
  return item;
}

// ── Completion ────────────────────────────────────────────────────────────

function importEditFor(doc, module) {
  const line = a.importInsertLine(doc.getText());
  return vscode.TextEdit.insert(new vscode.Position(line, 0), `importe "${module}"\n`);
}

function moduleItems(target, doc) {
  if (target.native) {
    return DATA.nativas
      .filter((n) => n.module === target.native)
      .flatMap((n) => [n.name, ...n.aliases].map((name) => nativeItem(n, name)));
  }
  const rel = path.relative(path.dirname(doc.uri.fsPath), target.file);
  return fileDefinitions(target.file).map((d) => defItem(d, rel));
}

function importItems(doc) {
  const items = DATA.modules.map((m) => {
    const it = new vscode.CompletionItem({ label: m, description: 'módulo nativo' }, vscode.CompletionItemKind.Module);
    const funcs = DATA.nativas.filter((n) => n.module === m).map((n) => n.name);
    it.detail = funcs.join(', ');
    return it;
  });
  // `.lep` files next to the document (and in subfolders), without extension.
  const base = path.dirname(doc.uri.fsPath);
  const found = [];
  const walk = (dir, depth) => {
    if (depth > 3 || found.length > 200) return;
    let entries = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.name.startsWith('.') || e.name === 'node_modules') continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full, depth + 1);
      else if (e.name.endsWith('.lep') && full !== doc.uri.fsPath) found.push(full);
    }
  };
  if (doc.uri.scheme === 'file') walk(base, 0);
  for (const f of found) {
    let rel = path.relative(base, f).split(path.sep).join('/').replace(/\.lep$/, '');
    // A bare name that is also a native module needs ./ to mean the file.
    if (DATA.modules.includes(rel)) rel = `./${rel}`;
    items.push(new vscode.CompletionItem({ label: rel, description: 'arquivo' }, vscode.CompletionItemKind.File));
  }
  return items;
}

function provideCompletion(doc, pos) {
  const before = doc.getText(new vscode.Range(new vscode.Position(0, 0), pos));
  const ctx = a.completionContext(before);
  if (ctx.kind === 'nenhum') return [];
  if (ctx.kind === 'importe') {
    // Replace the whole spec typed so far, `/` included.
    const range = new vscode.Range(pos.translate(0, -ctx.prefix.length), pos);
    return importItems(doc).map((it) => {
      it.range = range;
      return it;
    });
  }
  const sc = scope(doc);
  if (ctx.kind === 'modulo') {
    const target = sc.aliases.get(ctx.alias);
    if (target) return moduleItems(target, doc);
    // Not imported yet: `matriz::` still lists the native module.
    if (DATA.modules.includes(ctx.alias)) return moduleItems({ native: ctx.alias }, doc);
    return [];
  }
  const method = ctx.kind === 'metodo';
  const items = [];
  const seen = new Set();
  const push = (name, item) => {
    if (seen.has(name)) return;
    seen.add(name);
    items.push(item);
  };
  for (const d of sc.defs) {
    if (method && d.kind !== 'funcao') continue;
    push(d.name, defItem(d, 'neste arquivo', method));
  }
  for (const file of sc.files) {
    const rel = path.relative(path.dirname(doc.uri.fsPath), file);
    for (const d of fileDefinitions(file)) {
      if (method && d.kind !== 'funcao') continue;
      push(d.name, defItem(d, rel, method));
    }
  }
  for (const n of DATA.nativas) {
    if (method && (n.kind !== 'funcao' || a.signatureParams(n.signatures[0] || '').length === 0)) continue;
    let importEdit = null;
    if (n.module && !sc.spread.has(n.module)) {
      // Module only imported with an alias: use `alias::name` instead.
      if ([...sc.aliases.values()].some((t) => t.native === n.module)) continue;
      importEdit = importEditFor(doc, n.module);
    }
    for (const name of [n.name, ...n.aliases]) push(name, nativeItem(n, name, { method, importEdit }));
  }
  if (!method) {
    for (const [alias] of sc.aliases) {
      const it = new vscode.CompletionItem({ label: alias, description: 'módulo' }, vscode.CompletionItemKind.Module);
      it.insertText = `${alias}::`;
      it.command = { command: 'editor.action.triggerSuggest', title: '' };
      push(alias, it);
    }
    for (const k of KEYWORDS) push(k, new vscode.CompletionItem(k, vscode.CompletionItemKind.Keyword));
  }
  return items;
}

// ── Lookup shared by hover, signature help and definition ────────────────

/** Where `alias::name` or `name` comes from in `doc`. */
function lookup(doc, alias, name) {
  const sc = scope(doc);
  if (alias) {
    const target = sc.aliases.get(alias) || (DATA.modules.includes(alias) ? { native: alias } : null);
    if (!target) return null;
    if (target.native) {
      const n = NATIVE.get(name);
      return n && n.module === target.native ? { native: n } : null;
    }
    const d = fileDefinitions(target.file).find((x) => x.name === name);
    return d ? { def: d, file: target.file } : null;
  }
  const local = sc.defs.find((x) => x.name === name);
  if (local) return { def: local, file: doc.uri.fsPath, local: true };
  for (const file of sc.files) {
    const d = fileDefinitions(file).find((x) => x.name === name);
    if (d) return { def: d, file };
  }
  const n = NATIVE.get(name);
  return n ? { native: n } : null;
}

function provideHover(doc, pos) {
  const line = doc.lineAt(pos.line).text;
  const w = a.wordAt(line, pos.character);
  if (!w || KEYWORDS.includes(w.name)) return null;
  const found = lookup(doc, w.alias, w.name);
  if (!found) return null;
  const range = new vscode.Range(pos.line, w.start, pos.line, w.end);
  if (found.native) return new vscode.Hover(nativeMarkdown(found.native), range);
  const where = found.local ? `linha ${found.def.line + 1}` : `${path.basename(found.file)}, linha ${found.def.line + 1}`;
  return new vscode.Hover(defMarkdown(found.def, where), range);
}

function provideSignatureHelp(doc, pos) {
  const before = doc.getText(new vscode.Range(new vscode.Position(Math.max(0, pos.line - 30), 0), pos));
  const call = a.callContext(before);
  if (!call) return null;
  const found = lookup(doc, call.alias, call.name);
  if (!found) return null;
  const help = new vscode.SignatureHelp();
  if (found.native) {
    for (const sig of found.native.signatures) {
      const info = new vscode.SignatureInformation(sig, nativeMarkdown(found.native, false));
      info.parameters = a.signatureParams(sig).map((p) => new vscode.ParameterInformation(p));
      help.signatures.push(info);
    }
  } else if (found.def.kind === 'funcao') {
    const info = new vscode.SignatureInformation(defSignature(found.def));
    info.parameters = found.def.params.map((p) => new vscode.ParameterInformation(p));
    help.signatures.push(info);
  }
  if (!help.signatures.length) return null;
  // `x.f(a)` passes x as the first parameter.
  const active = call.active + (call.method ? 1 : 0);
  help.activeParameter = active;
  const fit = help.signatures.findIndex((s) => s.parameters.length > active || s.label.includes('...'));
  help.activeSignature = fit < 0 ? 0 : fit;
  return help;
}

function provideDefinition(doc, pos) {
  const line = doc.lineAt(pos.line).text;
  // `importe "lib/ajuda"`: jump to the file.
  const imp = line.match(/importe[ \t]+"([^"]+)"/u);
  if (imp) {
    const start = line.indexOf(`"${imp[1]}"`);
    if (pos.character >= start && pos.character <= start + imp[1].length + 2) {
      if (a.nativeModule(imp[1], DATA.modules)) return null;
      const file = a.resolveImport(imp[1], doc.uri.fsPath);
      return fs.existsSync(file) ? new vscode.Location(vscode.Uri.file(file), new vscode.Position(0, 0)) : null;
    }
  }
  const w = a.wordAt(line, pos.character);
  if (!w) return null;
  const found = lookup(doc, w.alias, w.name);
  if (!found || !found.def) return null;
  const uri = found.local ? doc.uri : vscode.Uri.file(found.file);
  return new vscode.Location(uri, new vscode.Position(found.def.line, 0));
}

function activate(context) {
  const sel = { language: LANG };
  context.subscriptions.push(
    vscode.languages.registerCompletionItemProvider(sel, { provideCompletionItems: provideCompletion }, '.', ':', '"', '/'),
    vscode.languages.registerHoverProvider(sel, { provideHover }),
    vscode.languages.registerSignatureHelpProvider(sel, { provideSignatureHelp }, '(', ','),
    vscode.languages.registerDefinitionProvider(sel, { provideDefinition }),
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
